### PR TITLE
Use "New Module Imports"

### PR DESCRIPTION
**Pull request by Turbo87**
see https://github.com/ember-cli/ember-rfc176-data

### CODE REVIEW

**Comment by Turbo87** [comment]
CI failure seems unrelated 😞

**Comment by machty** [comment]
Thanks! How does this work for older versions of Ember that want to use e-c?

**Comment by Turbo87** [comment]
`ember-cli-babel` will essentially just translate those imports into `const foo = Ember.foo`. Once Ember actually supports those import paths we'll use version detection in `ember-cli-babel` to disable that transform.

tl;dr it should just work 😉

**Comment by machty** [comment]
Does it require that all consumers of the new e-c also use babel 6.6.0? Or do addons get compiled with their preferred version of ember-cli-babel?

**Comment by Turbo87** [comment]
> do addons get compiled with their preferred version of ember-cli-babel

yep, that's how it works

**Comment by Turbo87** [comment]
@machty unfortunately I am very stupid and introduced a bug in this PR. My statement above about babel version used for the addon transpilation does not apply to the app folder but I've converted the files in there too. I'll fix that asap tomorrow. Sorry! 😞

**Pull request merged**
