### PR TITLE
Configure task property definitions (read/write)

### LINKED ISSUE #81: Task overriding broken in 0.7.11
In 0.7.10, overriding a task definition in an `extend` call worked as I'd expect a normal property override to, but with the getter changes in 0.7.11 it now throws `TypeError: Cannot set property go of [object Object] which has only a getter`.

```js
const MyThing = Ember.Object.extend({
  go: task(function*() { return 'yes'; })
});

const MyOtherThing = MyThing.extend({
  go: task(function*() { return 'actually, no'; })
});
```

### PR DESCRIPTION
**Pull request by sukima**
Make `configurable` and `writable`.

Closes #81

### CODE REVIEW

**Comment by machty** [comment]
@sukima thank you for the PR; Could you please provide a breaking test though? It should be reasonably easy to write below [this test](https://github.com/machty/ember-concurrency/blob/master/tests/unit/task-test.js#L237) and following a similar style. And this goes with out saying but make sure it actually breaks w the error reported in #81.

**Comment by machty** [comment]
Also does it need to be writable? or just configurable?

**Comment by dfreeman** [comment]
Aren't property descriptors either `writable`/`value` or `get`/`set`? What happens when you mix'n'match?

**Comment by machty** [comment]
subsumed by #83

**Pull request closed without merging**
