### PR TITLE
Exclude rx.js from npm package

### PR DESCRIPTION
**Pull request by jakesjews**

### CODE REVIEW

**Comment by machty** [comment]
Can you remind me why this is important to remove? Is it causing problems / bloat from consuming applications?

**Comment by jakesjews** [comment]
@machty just trying to reduce the amount of stuff downloaded with an NPM installed based on the overall story https://github.com/ember-cli/ember-cli/issues/6147. If you would rather keep it in the package I have no problem closing the PR.

**Comment by jakesjews** [comment]
If you use git for pulling down the test code you should be ok. This just excludes it from the published npm package.

**Comment by machty** [comment]
I did some cleanup and ended up removing this and some other things from the npm package. Thanks for the heads up :)

**Pull request closed without merging**
