### PR TITLE
Use class syntax for extending from ComputedProperty

### PR DESCRIPTION
**Pull request by ssutar**
Fix for https://github.com/machty/ember-concurrency/issues/261

### CODE REVIEW

**Comment by ssutar** [comment]
@rwjblue Updated

**Comment by rwjblue** [comment]
@ssutar - I think we should ensure that the current beta / canary failures are fixed before landing.

```
not ok 22 Chrome 70.0 - [undefined ms] - Global error: Uncaught Error: Assertion Failed: The first argument passed to the `cancel-all` helper should be a Task or TaskGroup (without quotes); you passed undefined at http://localhost:7357/assets/vendor.js, line 49231
 While executing test: Acceptance | helpers: perform and cancel-all
    ---
        Log: |
            { type: 'error',
              testContext: 
               { id: 22,
                 name: 'Acceptance | helpers: perform and cancel-all',
                 items: [],
                 state: 'executing' },
              text: 'Uncaught Error: Assertion Failed: The first argument passed to the `cancel-all` helper should be a Task or TaskGroup (without quotes); you passed undefined at http://localhost:7357/assets/vendor.js, line 49231\n' }
    ...
```

^ might be related to the changes here...

**Comment by ssutar** [comment]
Thanks @rwjblue Updated the RB with the `super` call. It was not needed in `3.1.1` (current version) however it is needed for beta and canary. 

I have to add a check against availability of `super` as its not accessible in current version.

**Comment by ssutar** [comment]
@rwjblue  Yeah, thats prettier :) Updated

**Pull request merged**
