### PR TITLE
Route tasks example: add this._super to setupController hook

### PR DESCRIPTION
**Pull request by mike-north**

### CODE REVIEW

**Comment by machty** [comment]
I feel like I should know this, but... is it necessary / good practice to call super() in setupController?

**Comment by mike-north** [comment]
If it's not, [this code](https://github.com/emberjs/ember.js/blob/306b88fd60739ae8179d8fdb9b3a2b53c5112a71/packages/ember-routing/lib/system/route.js#L1765-L1769) will not be invoked AFAIK

**Comment by machty** [comment]
I don't have strong opinions about this but seem fine.

**Comment by machty** [comment]
Also, thanks1

**Pull request merged**
