### PR TITLE
Enable testing against alpha builds.

### LINKED ISSUE #63: Prepare for 2.7.0 / glimmer
We'll need to update where we import the `INVOKE` keyword from for glimmer, specifically we'll need to try and import from here:

https://github.com/emberjs/ember.js/blob/master/packages/ember-glimmer/lib/helpers/action.js#L9

### PR DESCRIPTION
**Pull request by rwjblue**
Fix `INVOKE` symbol location for glimmer2.

Fixes #63.

### CODE REVIEW

**Comment by rwjblue** [comment]
There are 5 failures in the alpha channel at the moment. 4 are related to liquid-fire relying on glimmer1 semantics.  Removing liquid-fire fixes those tests.

**Comment by rwjblue** [comment]
Looks like liquid-fire is also failing on release branch.

**Comment by machty** [comment]
I'm just going to accept a broken build for now til LF settles/releases.

**Comment by rwjblue** [comment]
Sounds good.  Ping me in an issue/PR if you need me to poke at anything reported RE: alpha builds.

**Pull request merged**
