### PR TITLE
Issue #56 Fix bug when task is used outside an Ember object (e.g. test mock)

### PR DESCRIPTION
**Pull request by BryanCrotaz**
Add fix and test for using task outside Ember object

### CODE REVIEW

**Comment by osxi** [comment]
The fails pass locally for me so maybe it's a matter of retrying the Travis build?

**Comment by machty** [comment]
@osxi would you mind rebasing onto master? I believe you'll just have to update your test to `import { module } from 'qunit'`. I'll merge after that.

**Comment by osxi** [comment]
^ @BryanCrotaz

**Comment by machty** [comment]
Merged manually at https://github.com/machty/ember-concurrency/commit/a9967c4512eb57b39e7e8c001b1d52692b55ccbf

**Pull request closed without merging**
