### PR TITLE
generate jsdocs on ember build

### PR DESCRIPTION
**Pull request by billybonks**
https://github.com/machty/ember-concurrency/issues/13

Currently pointing to my repo, while i work on getting my changes merged with the upstream repo

### CODE REVIEW

**Comment by machty** [comment]
thank you!

**Comment by billybonks** [comment]
No problem :)

**Comment by machty** [comment]
@billybonks I'm just now noticing that this seems to cause an infinite rebuild loop; docs get rebuild, ember detects changes to dummy/public/api, rebuilds, etc etc etc.

I'm thinking maybe there's not a good way around this?

<details>
<summary>log</summary

file changed api/scripts/linenumber.js
file changed api/scripts/prettify/Apache-License-2.0.txt
file changed api/scripts/prettify/lang-css.js
file changed api/scripts/prettify/prettify.js
file changed api/styles/jsdoc-default.css
file changed api/styles/prettify-jsdoc.css
file changed api/styles/prettify-tomorrow.css
file changed api/fonts/OpenSans-Italic-webfont.woff
file changed api/fonts/OpenSans-Light-webfont.eot
file changed api/fonts/OpenSans-Light-webfont.svg
file changed api/fonts/OpenSans-LightItalic-webfont.eot
file changed api/fonts/OpenSans-Light-webfont.woff
file changed api/fonts/OpenSans-LightItalic-webfont.svg
file changed api/fonts/OpenSans-LightItalic-webfont.woff
file changed api/fonts/OpenSans-Regular-webfont.eot
file changed api/fonts/OpenSans-Regular-webfont.svg
file changed api/fonts/OpenSans-Regular-webfont.woff
file changed api/fonts/OpenSans-Bold-webfont.eot
file changed api/fonts/OpenSans-Bold-webfont.svg
file changed api/fonts/OpenSans-Bold-webfont.woff
file changed api/fonts/OpenSans-BoldItalic-webfont.eot
file changed api/fonts/OpenSans-BoldItalic-webfont.svg
file changed api/fonts/OpenSans-BoldItalic-webfont.woff
file changed api/fonts/OpenSans-Italic-webfont.eot
file changed api/fonts/OpenSans-Italic-webfont.svg
file changed dummy/public/api/yieldables.js.html
file changed dummy/public/api/index.js.html
file changed dummy/public/api/task-instance.js.html
file changed dummy/public/api/task-property.js.html
file changed dummy/public/api/scripts/linenumber.js
file changed dummy/public/api/scripts/prettify/Apache-License-2.0.txt
file changed dummy/public/api/scripts/prettify/lang-css.js
file changed dummy/public/api/scripts/prettify/prettify.js
file changed dummy/public/api/styles/jsdoc-default.css
file changed dummy/public/api/styles/prettify-jsdoc.css
file changed dummy/public/api/styles/prettify-tomorrow.css
file changed dummy/public/api/fonts/OpenSans-Italic-webfont.woff
file changed dummy/public/api/fonts/OpenSans-Light-webfont.eot
file changed dummy/public/api/fonts/OpenSans-Light-webfont.svg
file changed dummy/public/api/fonts/OpenSans-Light-webfont.woff
file changed dummy/public/api/fonts/OpenSans-LightItalic-webfont.eot
file changed dummy/public/api/fonts/OpenSans-LightItalic-webfont.svg
file changed dummy/public/api/fonts/OpenSans-LightItalic-webfont.woff
file changed dummy/public/api/fonts/OpenSans-Regular-webfont.eot
file changed dummy/public/api/fonts/OpenSans-Regular-webfont.svg
file changed dummy/public/api/fonts/OpenSans-Regular-webfont.woff
file changed dummy/public/api/fonts/OpenSans-Bold-webfont.eot
file changed dummy/public/api/fonts/OpenSans-Bold-webfont.svg
file changed dummy/public/api/fonts/OpenSans-Bold-webfont.woff
file changed dummy/public/api/fonts/OpenSans-BoldItalic-webfont.eot
file changed dummy/public/api/fonts/OpenSans-BoldItalic-webfont.svg
file changed dummy/public/api/fonts/OpenSans-BoldItalic-webfont.woff
file changed dummy/public/api/fonts/OpenSans-Italic-webfont.eot
file changed dummy/public/api/fonts/OpenSans-Italic-webfont.svg

EMBER-CLI-JSDOC: Documentation was successfully generated

Build successful - 3230ms.

Slowest Trees                                 | Total
----------------------------------------------+---------------------
BrowserifyWriter                              | 1552ms
Babel                                         | 233ms

Slowest Trees (cumulative)                    | Total (avg)
----------------------------------------------+---------------------
BrowserifyWriter (1)                          | 1552ms
Babel (17)                                    | 523ms (30 ms)

file changed dummy/public/api/TaskProperty.html
file changed dummy/public/api/TaskInstance.html
file changed dummy/public/api/Task.html
file changed dummy/public/api/global.html
file changed dummy/public/api/index.html
file changed api/TaskProperty.html
file changed api/TaskInstance.html
file changed api/Task.html
file changed api/global.html
file changed api/index.html

EMBER-CLI-JSDOC: Documentation was successfully generated

Build successful - 600ms.

Slowest Trees                                 | Total
----------------------------------------------+---------------------
BrowserifyWriter                              | 294ms
SourceMapConcat: Concat: Vendor               | 93ms
SassCompiler                                  | 49ms

Slowest Trees (cumulative)                    | Total (avg)
----------------------------------------------+---------------------
BrowserifyWriter (1)                          | 294ms
SourceMapConcat: Concat: Vendor (1)           | 93ms
SassCompiler (1)                              | 49ms

file changed api/Task.html
file changed api/TaskInstance.html
file changed api/TaskProperty.html
file changed api/yieldables.js.html
file changed api/task-instance.js.html
file changed api/index.js.html
file changed api/task-property.js.html
file changed api/global.html
file changed api/index.html
file changed api/fonts/OpenSans-Italic-webfont.woff
file changed api/fonts/OpenSans-Light-webfont.svg
file changed api/fonts/OpenSans-Light-webfont.eot
file changed api/fonts/OpenSans-Light-webfont.woff
file changed api/fonts/OpenSans-LightItalic-webfont.eot
file changed api/fonts/OpenSans-LightItalic-webfont.svg
file changed api/fonts/OpenSans-LightItalic-webfont.woff
file changed api/fonts/OpenSans-Regular-webfont.eot
file changed api/fonts/OpenSans-Regular-webfont.svg
file changed api/fonts/OpenSans-Regular-webfont.woff
file changed api/scripts/linenumber.js
file changed api/scripts/prettify/Apache-License-2.0.txt
file changed api/scripts/prettify/lang-css.js
file changed api/scripts/prettify/prettify.js
file changed api/styles/prettify-jsdoc.css
file changed api/styles/jsdoc-default.css
file changed api/styles/prettify-tomorrow.css
file changed api/fonts/OpenSans-Bold-webfont.eot
file changed api/fonts/OpenSans-Bold-webfont.svg
file changed api/fonts/OpenSans-Bold-webfont.woff
file changed api/fonts/OpenSans-BoldItalic-webfont.eot
file changed api/fonts/OpenSans-BoldItalic-webfont.svg
file changed api/fonts/OpenSans-BoldItalic-webfont.woff
file changed api/fonts/OpenSans-Italic-webfont.eot
file changed api/fonts/OpenSans-Italic-webfont.svg
file changed dummy/public/api/TaskInstance.html
file changed dummy/public/api/TaskProperty.html
file changed dummy/public/api/Task.html
file changed dummy/public/api/yieldables.js.html
file changed dummy/public/api/task-instance.js.html
file changed dummy/public/api/index.js.html
file changed dummy/public/api/task-property.js.html
file changed dummy/public/api/global.html
file changed dummy/public/api/index.html
file changed dummy/public/api/fonts/OpenSans-Italic-webfont.woff
file changed dummy/public/api/fonts/OpenSans-Light-webfont.eot
file changed dummy/public/api/fonts/OpenSans-LightItalic-webfont.eot
file changed dummy/public/api/fonts/OpenSans-Light-webfont.woff
file changed dummy/public/api/fonts/OpenSans-Light-webfont.svg
file changed dummy/public/api/fonts/OpenSans-LightItalic-webfont.svg
file changed dummy/public/api/fonts/OpenSans-LightItalic-webfont.woff
file changed dummy/public/api/fonts/OpenSans-Regular-webfont.eot
file changed dummy/public/api/fonts/OpenSans-Regular-webfont.svg
file changed dummy/public/api/fonts/OpenSans-Regular-webfont.woff
file changed dummy/public/api/scripts/linenumber.js
file changed dummy/public/api/scripts/prettify/Apache-License-2.0.txt
file changed dummy/public/api/scripts/prettify/lang-css.js
file changed dummy/public/api/scripts/prettify/prettify.js
file changed dummy/public/api/styles/prettify-jsdoc.css
file changed dummy/public/api/styles/jsdoc-default.css
file changed dummy/public/api/styles/prettify-tomorrow.css
file changed dummy/public/api/fonts/OpenSans-Bold-webfont.eot
file changed dummy/public/api/fonts/OpenSans-Bold-webfont.svg
file changed dummy/public/api/fonts/OpenSans-Bold-webfont.woff
file changed dummy/public/api/fonts/OpenSans-BoldItalic-webfont.eot
file changed dummy/public/api/fonts/OpenSans-BoldItalic-webfont.svg
file changed dummy/public/api/fonts/OpenSans-BoldItalic-webfont.woff
file changed dummy/public/api/fonts/OpenSans-Italic-webfont.eot
file changed dummy/public/api/fonts/OpenSans-Italic-webfont.svg

EMBER-CLI-JSDOC: Documentation was successfully generated

Build successful - 2141ms.

Slowest Trees                                 | Total
----------------------------------------------+---------------------
BrowserifyWriter                              | 1633ms
SnippetFinder                                 | 131ms

Slowest Trees (cumulative)                    | Total (avg)
----------------------------------------------+---------------------
BrowserifyWriter (1)                          | 1633ms
SnippetFinder (3)                             | 148ms (49 ms)

file changed api/TaskProperty.html
file changed api/Task.html
file changed api/TaskInstance.html
file changed api/yieldables.js.html
file changed api/task-instance.js.html
file changed api/index.js.html
file changed api/task-property.js.html
file changed api/global.html
file changed api/index.html
file changed api/fonts/OpenSans-Italic-webfont.woff
file changed api/fonts/OpenSans-Light-webfont.eot
file changed api/fonts/OpenSans-Light-webfont.svg
file changed api/fonts/OpenSans-Light-webfont.woff
file changed api/fonts/OpenSans-LightItalic-webfont.eot
file changed api/fonts/OpenSans-LightItalic-webfont.svg
file changed api/fonts/OpenSans-LightItalic-webfont.woff
file changed api/fonts/OpenSans-Regular-webfont.eot
file changed api/fonts/OpenSans-Regular-webfont.svg
file changed api/fonts/OpenSans-Regular-webfont.woff
file changed api/scripts/linenumber.js
file changed api/scripts/prettify/Apache-License-2.0.txt
file changed api/scripts/prettify/lang-css.js
file changed api/scripts/prettify/prettify.js
file changed api/styles/jsdoc-default.css
file changed api/styles/prettify-jsdoc.css
file changed api/styles/prettify-tomorrow.css
file changed api/fonts/OpenSans-Bold-webfont.eot
file changed api/fonts/OpenSans-Bold-webfont.svg
file changed api/fonts/OpenSans-Bold-webfont.woff
file changed api/fonts/OpenSans-BoldItalic-webfont.eot
file changed api/fonts/OpenSans-BoldItalic-webfont.woff
file changed api/fonts/OpenSans-BoldItalic-webfont.svg
file changed api/fonts/OpenSans-Italic-webfont.eot
file changed api/fonts/OpenSans-Italic-webfont.svg
file changed dummy/public/api/TaskProperty.html
file changed dummy/public/api/Task.html
file changed dummy/public/api/TaskInstance.html
file changed dummy/public/api/yieldables.js.html
file changed dummy/public/api/task-instance.js.html
file changed dummy/public/api/index.js.html
file changed dummy/public/api/task-property.js.html
file changed dummy/public/api/global.html
file changed dummy/public/api/index.html
file changed dummy/public/api/fonts/OpenSans-Italic-webfont.woff
file changed dummy/public/api/fonts/OpenSans-Light-webfont.eot
file changed dummy/public/api/fonts/OpenSans-Light-webfont.svg
file changed dummy/public/api/fonts/OpenSans-Light-webfont.woff
file changed dummy/public/api/fonts/OpenSans-LightItalic-webfont.eot
file changed dummy/public/api/fonts/OpenSans-LightItalic-webfont.svg
file changed dummy/public/api/fonts/OpenSans-LightItalic-webfont.woff
file changed dummy/public/api/fonts/OpenSans-Regular-webfont.eot
file changed dummy/public/api/fonts/OpenSans-Regular-webfont.svg
file changed dummy/public/api/fonts/OpenSans-Regular-webfont.woff
file changed dummy/public/api/scripts/linenumber.js
file changed dummy/public/api/scripts/prettify/Apache-License-2.0.txt
file changed dummy/public/api/scripts/prettify/lang-css.js
file changed dummy/public/api/scripts/prettify/prettify.js
file changed dummy/public/api/styles/jsdoc-default.css
file changed dummy/public/api/styles/prettify-jsdoc.css
file changed dummy/public/api/styles/prettify-tomorrow.css
file changed dummy/public/api/fonts/OpenSans-Bold-webfont.eot
file changed dummy/public/api/fonts/OpenSans-Bold-webfont.svg
file changed dummy/public/api/fonts/OpenSans-Bold-webfont.woff
file changed dummy/public/api/fonts/OpenSans-BoldItalic-webfont.eot
file changed dummy/public/api/fonts/OpenSans-BoldItalic-webfont.svg
file changed dummy/public/api/fonts/OpenSans-BoldItalic-webfont.woff
file changed dummy/public/api/fonts/OpenSans-Italic-webfont.eot
file changed dummy/public/api/fonts/OpenSans-Italic-webfont.svg

</details>

**Comment by billybonks** [comment]
oh that is terrible, hmm we could do it when you build for production ?

**Comment by billybonks** [comment]
@machty i am going to try get around this, in by checking if it's a dist build then generating the docs vs a ember serve build. will see what is available in the api 👍, sorry for the delay.

**Pull request merged**
