### PR TITLE
Ignore "Accessing __ec_cancel__ is deprecated" errors from Ember Data

### PR DESCRIPTION
**Pull request by Turbo87**
Resolves https://github.com/machty/ember-concurrency/issues/463

/cc @maxfierke

### CODE REVIEW

**Review by maxfierke — COMMENTED** [review]
@Turbo87 does replacing this with a `obj.hasOwnProperty(symbol)` check work? That might be preferable to swallowing an exception

**Comment by Turbo87** [comment]
```
Error: Accessing hasOwnProperty is deprecated.  Only available methods to access on a promise returned from model.save() are .then, .catch and .finally
```

unfortunately, that does not seem to work either :-/

/cc @runspired in case you have any suggestions

**Comment by maxfierke** [comment]
> ```
> Error: Accessing hasOwnProperty is deprecated.  Only available methods to access on a promise returned from model.save() are .then, .catch and .finally
> ```
> 
> unfortunately, that does not seem to work either :-/
> 
> /cc @runspired in case you have any suggestions

I would argue this is breaking an assumption that you should be able to call methods that a regular `Promise` would still have (which `hasOwnProperty` would be one, since it inherits it from `Object`)

However, if this is in a shipped/release version of Ember Data, we should move forward with the `try/catch`

**Comment by Turbo87** [comment]
I just realized that this is causing issues for us because we are using https://github.com/mixonic/ember-cli-deprecation-workflow with `throwOnUnhandled: true`, which turns regular deprecation warnings into `throw theDeprecation`. Ignoring the deprecation instead fixes the issue too, so there is actually no need for changing anything in ember-concurrency :)

**Pull request closed without merging**
